version: '3'

volumes:
  db_data: { }
  django_data: { }

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_data:/app/trello2/media
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: library/postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5442:5432
