version: '3'

volumes:
  postgres_data: {}
  django_data: {}
#  pgadmin_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_data:/app/trello2/media
    ports:
      - 8080:8000
    env_file:
      - .env

  postgres:
    image: library/postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5442:5432

#  pgadmin:
#    image: library/postgres:13
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin/data
#    env_file:
#      - envs/pgadmin-env.list
#    ports:
#      - 5050:5050