# Generated by Django 3.1.5 on 2021-02-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_board', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_column', models.CharField(max_length=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('fact', models.CharField(max_length=511, null=True)),
                ('weather', models.FloatField(null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.column')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionOnBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'permission',
                    models.IntegerField(choices=[(1, 'Owner'), (2, 'Member'), (3, 'Visitor'), (4, 'Admin')])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(through='table.PermissionOnBoard', to=settings.AUTH_USER_MODEL),
        ),
    ]
