# Generated by Django 3.1.5 on 2021-01-14 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.column')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='columns',
            field=models.ManyToManyField(through='table.ColumnBoard', to='table.Column'),
        ),
    ]
